#!/usr/bin/env python3
'''pybar'''

from lib_pybar import __main__ as pybar
from lib_pybar.signals import flags

if __name__ == '__main__':
    try:
        pybar.main()
    except (EOFError, KeyboardInterrupt):
        flags.abort = True

    if flags.abort:
        exit(1)
